pip install pip --upgrade
pip install docutils --upgrade
pip install fpdf --upgrade
pip install importlib_metadata --upgrade
pip install markdown --upgrade
pip install ofxtools --upgrade
pip install openpyxl --upgrade
pip install pillow --upgrade
pip install progress --upgrade
pip install psycopg2 --upgrade
pip install pyaes --upgrade
pip install pycryptodome --upgrade
pip install pyexcel --upgrade
pip install pyexcel-ods --upgrade
pip install pygal --upgrade
pip install pyinstaller --upgrade
pip install pymupdf --upgrade
pip install pysmb --upgrade
pip install pywin32 --upgrade
pip install requests --upgrade
pip install send2trash --upgrade
pip install setuptools --upgrade
pip install svglib --upgrade
pip install tkcolorpicker --upgrade
pip install tkinterhtml --upgrade
